[project]
name = "medical-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.4",
    "dbt-snowflake>=1.12.0",
]

[project.scripts]
medical-dbt = "medical_dbt:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
